/*drop database filmesdb;*/
create database filmesdb;
use filmesdb;

create table filme (
	id int primary key auto_increment,
    nome varchar(255) not null,
    ano int not null,
    descricao text,
    urlIMG text
);

insert into filme (nome, ano, descricao, urlIMG) values ('Um Sonho de Liberdade', 1994, 'Dois homens presos se reúnem ao longo de vários anos, encontrando consolo e eventual redenção através de atos de decência comum.','https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/90/16/48/20083748.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('O Poderoso Chefão', 1972, 'O patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.','https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/90/93/20/20120876.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Batman: O Cavaleiro das Trevas', 2008, 'Agora com a ajuda do tenente Jim Gordon e do promotor público Harvey Dent, Batman tem tudo para banir o crime de Gotham City de uma vez por todas. Mas em breve, os três serão vítimas do Coringa, que pretende lançar Gotham em uma anarquia.','https://br.web.img2.acsta.net/c_310_420/medias/nmedia/18/90/57/96/20121842.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('O Poderoso Chefão: Parte II', 1974, 'Em 1950, Michael Corleone, agora à frente da família, tenta expandir o negócio do crime a Las Vegas, Los Angeles e Cuba. Paralelamente, é revelada a história de Vito Corleone, e de como saiu da Sicília e chegou a Nova Iorque.','https://br.web.img2.acsta.net/c_310_420/medias/nmedia/18/90/93/27/20120933.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('12 Homens e uma Sentença', 1957, 'O julgamento de um assassinato em Nova Iorque é frustrado por um único membro, cujo ceticismo força o júri a considerar cuidadosamente as evidências antes de dar o veredito.','https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/94/89/49/20363466.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('O Senhor dos Anéis: O Retorno do Rei', 2003, 'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar de Frodo e Sam quando eles se aproximam á Montanha da Perdição com o Um Anel.','https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/92/91/47/20224867.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('A Lista de Schindler', 1993, 'Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, o industrial Oskar Schindler começa a ser preocupar com seus trabalhadores judeus depois de testemunhar sua perseguição pelos nazistas.','https://br.web.img3.acsta.net/c_310_420/pictures/19/04/10/19/44/2904073.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Pulp Fiction: Tempo de Violência', 1994, 'As vidas de dois assassinos da máfia, um boxeador, um gângster e sua esposa, e um par de bandidos se entrelaçam em quatro histórias de violência e redenção.','https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/87/16/32/19872655.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('O Senhor dos Anéis: A Sociedade do Anel', 2001, 'Um manso hobbit do Condado e oito companheiros partem em uma jornada para destruir o poderoso Um Anel e salvar a Terra-média das Trevas.','https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/92/91/32/20224832.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Três Homens em Conflito', 1966, 'Um impostor se junta com dois homens para encontrar fortuna num remoto cemitério.','https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/97/53/07/20534288.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Oppenheimer', 2023, 'O físico J. Robert Oppenheimer trabalha com uma equipe de cientistas durante o Projeto Manhattan, levando ao desenvolvimento da bomba atômica.','https://br.web.img3.acsta.net/c_310_420/pictures/23/05/08/10/29/0695770.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Homem-Aranha: Através do Aranhaverso', 2023, 'Depois de se reunir com Gwen Stacy, Homem-Aranha é jogado no multiverso. Lá, o super-herói aracnídeo encontra uma numerosa equipe encarregada de proteger sua própria existência.','https://br.web.img2.acsta.net/c_310_420/pictures/23/05/17/22/43/4869322.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Barbie', 2023, 'Depois de ser expulsa da Barbieland por ser uma boneca de aparência menos do que perfeita, Barbie parte para o mundo humano em busca da verdadeira felicidade.','https://br.web.img2.acsta.net/c_310_420/pictures/23/06/21/21/10/1335465.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('John Wick 4: Baba Yaga', 2023, 'O ex-assassino de aluguel John Wick é procurado pelo mundo todo e a recompensa por sua captura aumenta cada vez mais. Wick descobre um caminho para derrotar a Alta Cúpula, mas antes de conquistar sua liberdade, ele precisa enfrentar um novo inimigo com alianças poderosas e forças que transformam velhos amigos em inimigos.','https://br.web.img2.acsta.net/c_310_420/pictures/22/12/05/09/07/2007563.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Guardiões da Galáxia Vol. 3', 2023, 'Peter Quill deve reunir sua equipe para defender o universo e proteger um dos seus. Se a missão não for totalmente bem-sucedida, isso pode levar ao fim dos Guardiões.','https://br.web.img3.acsta.net/c_310_420/pictures/23/04/25/20/10/1515852.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Assassinos da Lua das Flores', 2023, 'Os assassinatos dados a partir de circunstâncias misteriosas na década de 1920, assolando os membros da tribo Osage, acaba desencadeando uma grande investigação envolvendo o poderoso J. Edgar Hoover, considerado o primeiro diretor do FBI.','https://br.web.img3.acsta.net/c_310_420/pictures/23/09/13/16/59/5541526.png');
insert into filme (nome, ano, descricao, urlIMG) values ('Missão: Impossível - Acerto de Contas Parte Um', 2023, 'Ethan Hunt e sua equipe devem rastrear uma nova arma que pode ameaçar toda a humanidade se cair em mãos erradas. Com o destino do mundo em jogo, se inicia uma corrida mortal ao redor do globo. Confrontado por um inimigo misterioso e poderoso, Ethan é forçado a considerar que talvez nada importe mais do que a missão, nem mesmo as vidas daqueles com quem ele mais se importa.','https://br.web.img3.acsta.net/c_310_420/pictures/23/06/21/21/16/0102047.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Dungeons & Dragons: Honra Entre Rebeldes', 2023, 'Um ladrão e um bando de aventureiros embarcam em uma jornada épica para recuperar uma relíquia.','https://br.web.img3.acsta.net/c_310_420/pictures/22/12/08/18/11/4403832.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Indiana Jones e a Relíquia do Destino', 2023, 'O lendário herói arqueólogo está de volta neste aguardado capítulo final da icônica franquia, uma incrível e empolgante aventura cinematográfica.','https://br.web.img3.acsta.net/c_310_420/pictures/23/04/10/17/56/1153346.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('As Tartarugas Ninja: Caos Mutante', 2023, 'Os irmãos Tartaruga enfrentam um misterioso crime, mas logo se metem em confusão quando um exército de mutantes é lançado sobre eles.','https://br.web.img3.acsta.net/c_310_420/pictures/23/05/31/17/15/1765372.jpg');
insert into filme (nome, ano, descricao, urlIMG) values ('Putz! A Coisa Tá Feia', 2006,'Ratso, um roedor esfomeado, convence a todos de que ele é o pai do patinho feio. Ratso e o patinho mais feio do mundo partem para uma arriscada jornada com inimigos perigosos, problemas de adolescentes e sentimentos paternos inesperados esperando-os pela frente.','https://upload.wikimedia.org/wikipedia/pt/thumb/e/e3/The_Ugly_Duckling_and_Me%21_%28capa%29.jpeg/200px-The_Ugly_Duckling_and_Me%21_%28capa%29.jpeg'); 




